schema_version: 1

context:
  version: 1.2.2

package:
  name: wdiff
  version: ${{ version }}

source:
  url: http://ftp.gnu.org/gnu/wdiff/wdiff-${{ version }}.tar.gz
  sha256: 34ff698c870c87e6e47a838eeaaae729fa73349139fc8db12211d2a22b78af6b

build:
  number: 2
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gettext-tools
    - make
    - texinfo
    - xz-tools
  host:
    - if: not linux
      then: libintl-devel
    - libtool
    - ncurses

tests:
  - script:
      - wdiff --version

about:
  license: GPL-3.0-only
  license_file: COPYING
  summary: Word based diff
  description: |
    `wdiff' is a front-end to GNU `diff'.  It compares two files, finding
    which words have been deleted or added to the first in order to create
    the second.  It has many output formats and interacts well with
    terminals and pagers (notably with `less').  `wdiff' is particularly
    useful when two texts differ only by a few words and paragraphs have
    been refilled.
  homepage: https://www.gnu.org/software/wdiff/
  repository: https://www.gnu.org/software/wdiff/
  documentation: https://www.gnu.org/software/wdiff/manual/wdiff.html

extra:
  recipe-maintainers:
    - danielnachun
    - corneliusroemer
